from typing import Protocol
from decimal import Decimal

class ICbs(Protocol):
    def valor_base_ibs_cbs(self) -> Decimal: ...
    def aliquota_efetiva(self) -> Decimal: ...
    def diferimento(self) -> Decimal: ...
    def valor_cbs(self) -> Decimal: ...

class ICofins01_02(Protocol):
    def base_cofins(self) -> Decimal: ...
    def valor_cofins(self) -> Decimal: ...

class ICofins03(Protocol):
    def valor_cofins(self) -> Decimal: ...

class IFcp(Protocol):
    def valor_fcp(self) -> Decimal: ...

class IFcpDif(Protocol):
    def valor_fcp_diferido(self) -> Decimal: ...

class IFcpEfet(Protocol):
    def valor_fcp_efetivo(self) -> Decimal: ...

class IFcpST(Protocol):
    def valor_fcp_st(self) -> Decimal: ...

class IIbsUf(Protocol):
    def valor_base_ibs_cbs(self) -> Decimal: ...
    def aliquota_efetiva(self) -> Decimal: ...
    def diferimento(self) -> Decimal: ...
    def valor_ibs_uf(self) -> Decimal: ...

class IIcms00(Protocol):
    def base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...

class IIcms10(Protocol):
    def base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def base_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...
    def valor_icms_st_desonerado(self) -> Decimal: ...

class IIcms101(Protocol):
    def calcular_base_icms_proprio(self) -> Decimal: ...
    def valor_credito_sn(self) -> Decimal: ...

class IIcms20(Protocol):
    def base_reduzida_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def valor_icms_desonerado(self) -> Decimal: ...

class IIcms201(Protocol):
    def calcular_base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def valor_credito_sn(self) -> Decimal: ...
    def base_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...

class IIcms202_203(Protocol):
    def calcular_base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def base_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...

class IIcms30(Protocol):
    def base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def base_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...
    def valor_icms_desonerado(self) -> Decimal: ...

class IIcms51(Protocol):
    def base_icms_proprio(self) -> Decimal: ...
    def valor_icms_operacao(self) -> Decimal: ...
    def valor_icms_diferido(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...

class IIcms70(Protocol):
    def base_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio_desonerado(self) -> Decimal: ...
    def base_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...
    def valor_icms_st_desonerado(self) -> Decimal: ...

class IIcms90(Protocol):
    def calcular_base_icms_proprio(self) -> Decimal: ...
    def calcular_base_reduzida_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio_base_reduzida(self) -> Decimal: ...
    def valor_icms_proprio_desonerado(self) -> Decimal: ...
    def calcular_base_icms_st(self) -> Decimal: ...
    def calcular_base_reduzida_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...
    def valor_icms_st_base_reduzida(self) -> Decimal: ...
    def valor_icms_st_desonerado(self) -> Decimal: ...

class IIcms900(Protocol):
    def calcular_base_icms_proprio(self) -> Decimal: ...
    def calcular_base_reduzida_icms_proprio(self) -> Decimal: ...
    def valor_icms_proprio(self) -> Decimal: ...
    def valor_credito_sn(self) -> Decimal: ...
    def valor_icms_proprio_base_reduzida(self) -> Decimal: ...
    def calcular_base_icms_st(self) -> Decimal: ...
    def calcular_base_reduzida_icms_st(self) -> Decimal: ...
    def valor_icms_st(self) -> Decimal: ...
    def valor_icms_st_base_reduzida(self) -> Decimal: ...

class IIpi50AdValorem(Protocol):
    def calcular_base_ipi(self) -> Decimal: ...
    def valor_ipi(self) -> Decimal: ...

class IIpiEspecifico(Protocol):
    def valor_ipi(self) -> Decimal: ...

class IPis01_02(Protocol):
    def base_pis(self) -> Decimal: ...
    def valor_pis(self) -> Decimal: ...

class IPis03(Protocol):
    def valor_pis(self) -> Decimal: ...
